import io

import discord
from discord.ext import commands

from utils.input_source import get_code_input
from utils.minifier_lua import minify

HEADER = "-- [[ This file is generated by MinifierLuaBot ]]\n"

# NOTE: This is a lightweight obfuscator (minify + randomize local variable
# names). There is NO Anti-Tamper / Custom VM / Custom Bytecode / junk-code
# injection -- the levels below only differ in how "strong" the renaming and
# minifying is.
LEVEL_CONFIG = {
    1: dict(rename=False, keep_comments=False, min_len=3, max_len=3, label="Level 1 - Minify only"),
    2: dict(rename=True, keep_comments=False, min_len=2, max_len=3, label="Level 2 - Minify + short rename"),
    3: dict(rename=True, keep_comments=False, min_len=4, max_len=6, label="Level 3 - Minify + medium rename"),
    4: dict(rename=True, keep_comments=False, min_len=6, max_len=10, label="Level 4 - Minify + long rename"),
}


async def _send_result(ctx: commands.Context, code: str, filename: str, label: str):
    result = HEADER + code
    if len(result) <= 1900:
        await ctx.send(f"**{label}**\n```lua\n{result}\n```")
    else:
        buf = io.BytesIO(result.encode("utf-8"))
        await ctx.send(f"**{label}**", file=discord.File(buf, filename=filename))


class Obfuscate(commands.Cog):
    def __init__(self, bot: commands.Bot):
        self.bot = bot

    @commands.command(name="obf")
    async def obf(self, ctx: commands.Context, level: int = 2, *, arg: str = None):
        """Lightweight obfuscation (minify + rename variables). Level 1-4.
        Example: .obf 3 (attach a file / URL / paste code)
        """
        if level not in LEVEL_CONFIG:
            await ctx.send("Level must be one of: 1, 2, 3, 4.")
            return

        async with ctx.typing():
            try:
                code = await get_code_input(ctx, arg)
            except ValueError as e:
                await ctx.send(f"❌ {e}")
                return

            cfg = LEVEL_CONFIG[level]
            try:
                result = minify(
                    code,
                    keep_comments=cfg["keep_comments"],
                    rename=cfg["rename"],
                    min_name_len=cfg["min_len"],
                    max_name_len=cfg["max_len"],
                )
            except Exception as e:
                await ctx.send(f"❌ Obfuscation failed: `{e}`")
                return

        await _send_result(ctx, result, "obfuscated.lua", cfg["label"])


async def setup(bot: commands.Bot):
    await bot.add_cog(Obfuscate(bot))
